#!/bin/bash 
 IMAGE_NAME=aalmann/gh-cli

if [[ -z "$GH_TOKEN" ]]; then 
    TOKEN_ENV=""
    echo No token GH_TOKEN given
else
    TOKEN_ENV=" -e GH_TOKEN=${GH_TOKEN}"
    echo GH_TOKEN found in environment. Will using it.
fi

docker run ${TOKEN_ENV} -v `pwd`:/gh $IMAGE_NAME $@